Fix bug in router with python2
- This code seems to have been added awhile ago, but never really
  tested in python 2. We shouldn't convert strings to unicode in
  python 2 when receiving messages. This causes a TypeError when
  forwarding messages:
  ```
  TypeError: Frame 0 (u'719ff6da-ac33-4273-a2bc-6cb9b4...) does not
  support the buffer interface.
  ```

References: 55963796809ce5aacf47c24d8295ab5b1a500ad1